let Product=[
{
"id": 1,
"title": "Essence Mascara Lash Princess",
"description": "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
"price": 9.99,
"brand": "Essence",
},
{
"id": 2,
"title": "Eyeshadow Palette with Mirror",
"description": "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
"category": "beauty",
"price": 19.99,
"brand": "Glamour Beauty",
},
{
"id": 3,
"title": "Powder Canister",
"description": "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
"category": "beauty",
"price": 14.99,
"brand": "Velvet Touch",
},
{
"id": 4,
"title": "Red Lipstick",
"description": "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
"category": "beauty",
"price": 12.99,
"brand": "Chic Cosmetics",
},
{
"id": 5,
"title": "Red Nail Polish",
"description": "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
"category": "beauty",
"price": 8.99,
"brand": "Nail Couture",
},
{
"id": 6,
"title": "Calvin Klein CK One",
"description": "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
"category": "fragrances",
"price": 49.99,
"brand": "Calvin Klein",
},
{
"id": 7,
"title": "Chanel Coco Noir Eau De",
"description": "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
"category": "fragrances",
"price": 129.99,
"brand": "Chanel",
},
{
"id": 8,
"title": "Dior J'adore",
"description": "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
"category": "fragrances",
"price": 89.99,
"brand": "Dior",
},
{
"id": 9,
"title": "Dolce Shine Eau de",
"description": "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
"category": "fragrances",
"price": 69.99,
"brand": "Dolce & Gabbana",
},
{
"id": 10,
"title": "Gucci Bloom Eau de",
"description": "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
"category": "fragrances",
"price": 79.99,
"brand": "Gucci",
},
{
"id": 11,
"title": "Annibale Colombo Bed",
"description": "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
"category": "furniture",
"price": 1899.99,
"brand": "Annibale Colombo",
},
{
"id": 12,
"title": "Annibale Colombo Sofa",
"description": "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
"category": "furniture",
"price": 2499.99,
"brand": "Annibale Colombo",
},
{
"id": 13,
"title": "Bedside Table African Cherry",
"description": "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
"category": "furniture",
"price": 299.99,
"brand": "Furniture Co.",
},
{
"id": 14,
"title": "Knoll Saarinen Executive Conference Chair",
"description": "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
"category": "furniture",
"price": 499.99,
"brand": "Knoll",
},
{
"id": 15,
"title": "Wooden Bathroom Sink With Mirror",
"description": "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
"category": "furniture",
"price": 799.99,
"brand": "Bath Trends",
},
{
"id": 16,
"title": "Apple",
"description": "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
"category": "groceries",
"price": 1.99,
"brand": "Bath",
},
{
"id": 17,
"title": "Beef Steak",
"description": "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
"category": "groceries",
"price": 12.99,
"brand": "Hokaido",
},
{
"id": 18,
"title": "Cat Food",
"description": "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
"category": "groceries",
"price": 8.99,
"brand": "Cat guard",
},
{
"id": 19,
"title": "Chicken Meat",
"description": "Fresh and tender chicken meat, suitable for various culinary preparations.",
"category": "groceries",
"price": 9.99,
"brand": "Chicken gunia",
},
{
"id": 20,
"title": "Cooking Oil",
"description": "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
"category": "groceries",
"price": 4.99,
"brand": "Rupchada",
},
{
"id": 21,
"title": "Cucumber",
"description": "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
"category": "groceries",
"price": 1.49,
"brand": "Mamu",
},
{
"id": 22,
"title": "Dog Food",
"description": "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
"category": "groceries",
"price": 10.99,
"brand": "Dogeshvai",
},
{
"id": 23,
"title": "Eggs",
"description": "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
"category": "groceries",
"price": 2.99,
"brand": "Chicken or Egg",
},
{
"id": 24,
"title": "Fish Steak",
"description": "Quality fish steak, suitable for grilling, baking, or pan-searing.",
"category": "groceries",
"price": 14.99,
"brand": "Fish",
},
{
"id": 25,
"title": "Green Bell Pepper",
"description": "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
"category": "groceries",
"price": 1.29,
"brand": "Kacha Bazzar",
},
{
"id": 26,
"title": "Green Chili Pepper",
"description": "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
"category": "groceries",
"price": 0.99,
"brand": "Kacha Bazaar",
},
{
"id": 27,
"title": "Honey Jar",
"description": "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
"category": "groceries",
"price": 6.99,
"brand": "Machir Juice",
},
{
"id": 28,
"title": "Ice Cream",
"description": "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
"category": "groceries",
"price": 5.49,
"brand": "Cow Ice",
},
{
"id": 29,
"title": "Juice",
"description": "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
"category": "groceries",
"price": 3.99,
"brand": "Tree milk",
},
{
"id": 30,
"title": "Kiwi",
"description": "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
"category": "groceries",
"price": 2.49,
"brand": "Fol",
},
{
"id": 31,
"title": "Essence Mascara Lash Princess",
"description": "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
"price": 9.99,
"brand": "Essence",
},
{
"id": 32,
"title": "Eyeshadow Palette with Mirror",
"description": "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
"category": "beauty",
"price": 19.99,
"brand": "Glamour Beauty",
},
{
"id": 33,
"title": "Powder Canister",
"description": "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
"category": "beauty",
"price": 14.99,
"brand": "Velvet Touch",
},
{
"id": 34,
"title": "Red Lipstick",
"description": "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
"category": "beauty",
"price": 12.99,
"brand": "Chic Cosmetics",
},
{
"id": 35,
"title": "Red Nail Polish",
"description": "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
"category": "beauty",
"price": 8.99,
"brand": "Nail Couture",
},
{
"id": 36,
"title": "Calvin Klein CK One",
"description": "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
"category": "fragrances",
"price": 49.99,
"brand": "Calvin Klein",
},
{
"id": 37,
"title": "Chanel Coco Noir Eau De",
"description": "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
"category": "fragrances",
"price": 129.99,
"brand": "Chanel",
},
{
"id": 38,
"title": "Dior J'adore",
"description": "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
"category": "fragrances",
"price": 89.99,
"brand": "Dior",
},
{
"id": 39,
"title": "Dolce Shine Eau de",
"description": "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
"category": "fragrances",
"price": 69.99,
"brand": "Dolce & Gabbana",
},
{
"id": 40,
"title": "Gucci Bloom Eau de",
"description": "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
"category": "fragrances",
"price": 79.99,
"brand": "Gucci",
},
{
"id": 41,
"title": "Annibale Colombo Bed",
"description": "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
"category": "furniture",
"price": 1899.99,
"brand": "Annibale Colombo",
},
{
"id": 42,
"title": "Annibale Colombo Sofa",
"description": "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
"category": "furniture",
"price": 2499.99,
"brand": "Annibale Colombo",
},
{
"id": 43,
"title": "Bedside Table African Cherry",
"description": "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
"category": "furniture",
"price": 299.99,
"brand": "Furniture Co.",
},
{
"id": 44,
"title": "Knoll Saarinen Executive Conference Chair",
"description": "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
"category": "furniture",
"price": 499.99,
"brand": "Knoll",
},
{
"id": 45,
"title": "Wooden Bathroom Sink With Mirror",
"description": "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
"category": "furniture",
"price": 799.99,
"brand": "Bath Trends",
},
{
"id": 46,
"title": "Apple",
"description": "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
"category": "groceries",
"price": 1.99,
"brand": "Bath",
},
{
"id": 47,
"title": "Beef Steak",
"description": "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
"category": "groceries",
"price": 12.99,
"brand": "Hokaido",
},
{
"id": 48,
"title": "Cat Food",
"description": "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
"category": "groceries",
"price": 8.99,
"brand": "Cat guard",
},
{
"id": 49,
"title": "Chicken Meat",
"description": "Fresh and tender chicken meat, suitable for various culinary preparations.",
"category": "groceries",
"price": 9.99,
"brand": "Chicken gunia",
},
{
"id": 50,
"title": "Cooking Oil",
"description": "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
"category": "groceries",
"price": 4.99,
"brand": "Rupchada",
},
{
"id": 51,
"title": "Cucumber",
"description": "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
"category": "groceries",
"price": 1.49,
"brand": "Mamu",
},
{
"id": 22,
"title": "Dog Food",
"description": "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
"category": "groceries",
"price": 10.99,
"brand": "Dogeshvai",
},
{
"id": 53,
"title": "Eggs",
"description": "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
"category": "groceries",
"price": 2.99,
"brand": "Chicken or Egg",
},
{
"id": 54,
"title": "Fish Steak",
"description": "Quality fish steak, suitable for grilling, baking, or pan-searing.",
"category": "groceries",
"price": 14.99,
"brand": "Fish",
},
{
"id": 55,
"title": "Green Bell Pepper",
"description": "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
"category": "groceries",
"price": 1.29,
"brand": "Kacha Bazzar",
},
{
"id": 56,
"title": "Green Chili Pepper",
"description": "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
"category": "groceries",
"price": 0.99,
"brand": "Kacha Bazaar",
},
{
"id": 57,
"title": "Honey Jar",
"description": "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
"category": "groceries",
"price": 6.99,
"brand": "Machir Juice",
},
{
"id": 58,
"title": "Ice Cream",
"description": "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
"category": "groceries",
"price": 5.49,
"brand": "Cow Ice",
},
{
"id": 59,
"title": "Juice",
"description": "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
"category": "groceries",
"price": 3.99,
"brand": "Tree milk",
},
{
"id": 60,
"title": "Kiwi",
"description": "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
"category": "groceries",
"price": 2.49,
"brand": "Fol",
},
{
"id": 61,
"title": "Essence Mascara Lash Princess",
"description": "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
"price": 9.99,
"brand": "Essence",
},
{
"id": 62,
"title": "Eyeshadow Palette with Mirror",
"description": "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
"category": "beauty",
"price": 19.99,
"brand": "Glamour Beauty",
},
{
"id": 63,
"title": "Powder Canister",
"description": "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
"category": "beauty",
"price": 14.99,
"brand": "Velvet Touch",
},
{
"id": 64,
"title": "Red Lipstick",
"description": "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
"category": "beauty",
"price": 12.99,
"brand": "Chic Cosmetics",
},
{
"id": 65,
"title": "Red Nail Polish",
"description": "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
"category": "beauty",
"price": 8.99,
"brand": "Nail Couture",
},
{
"id": 66,
"title": "Calvin Klein CK One",
"description": "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
"category": "fragrances",
"price": 49.99,
"brand": "Calvin Klein",
},
{
"id": 67,
"title": "Chanel Coco Noir Eau De",
"description": "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
"category": "fragrances",
"price": 129.99,
"brand": "Chanel",
},
{
"id": 68,
"title": "Dior J'adore",
"description": "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
"category": "fragrances",
"price": 89.99,
"brand": "Dior",
},
{
"id": 69,
"title": "Dolce Shine Eau de",
"description": "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
"category": "fragrances",
"price": 69.99,
"brand": "Dolce & Gabbana",
},
{
"id": 70,
"title": "Gucci Bloom Eau de",
"description": "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
"category": "fragrances",
"price": 79.99,
"brand": "Gucci",
},
{
"id": 71,
"title": "Annibale Colombo Bed",
"description": "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
"category": "furniture",
"price": 1899.99,
"brand": "Annibale Colombo",
},
{
"id": 72,
"title": "Annibale Colombo Sofa",
"description": "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
"category": "furniture",
"price": 2499.99,
"brand": "Annibale Colombo",
},
{
"id": 73,
"title": "Bedside Table African Cherry",
"description": "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
"category": "furniture",
"price": 299.99,
"brand": "Furniture Co.",
},
{
"id": 74,
"title": "Knoll Saarinen Executive Conference Chair",
"description": "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
"category": "furniture",
"price": 499.99,
"brand": "Knoll",
},
{
"id": 75,
"title": "Wooden Bathroom Sink With Mirror",
"description": "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
"category": "furniture",
"price": 799.99,
"brand": "Bath Trends",
},
{
"id": 76,
"title": "Apple",
"description": "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
"category": "groceries",
"price": 1.99,
"brand": "Bath",
},
{
"id": 77,
"title": "Beef Steak",
"description": "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
"category": "groceries",
"price": 12.99,
"brand": "Hokaido",
},
{
"id": 78,
"title": "Cat Food",
"description": "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
"category": "groceries",
"price": 8.99,
"brand": "Cat guard",
},
{
"id": 79,
"title": "Chicken Meat",
"description": "Fresh and tender chicken meat, suitable for various culinary preparations.",
"category": "groceries",
"price": 9.99,
"brand": "Chicken gunia",
},
{
"id": 80,
"title": "Cooking Oil",
"description": "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
"category": "groceries",
"price": 4.99,
"brand": "Rupchada",
},
{
"id": 81,
"title": "Cucumber",
"description": "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
"category": "groceries",
"price": 1.49,
"brand": "Mamu",
},
{
"id": 82,
"title": "Dog Food",
"description": "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
"category": "groceries",
"price": 10.99,
"brand": "Dogeshvai",
},
{
"id": 83,
"title": "Eggs",
"description": "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
"category": "groceries",
"price": 2.99,
"brand": "Chicken or Egg",
},
{
"id": 84,
"title": "Fish Steak",
"description": "Quality fish steak, suitable for grilling, baking, or pan-searing.",
"category": "groceries",
"price": 14.99,
"brand": "Fish",
},
{
"id": 85,
"title": "Green Bell Pepper",
"description": "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
"category": "groceries",
"price": 1.29,
"brand": "Kacha Bazzar",
},
{
"id": 86,
"title": "Green Chili Pepper",
"description": "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
"category": "groceries",
"price": 0.99,
"brand": "Kacha Bazaar",
},
{
"id": 87,
"title": "Honey Jar",
"description": "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
"category": "groceries",
"price": 6.99,
"brand": "Machir Juice",
},
{
"id": 88,
"title": "Ice Cream",
"description": "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
"category": "groceries",
"price": 5.49,
"brand": "Cow Ice",
},
{
"id": 89,
"title": "Juice",
"description": "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
"category": "groceries",
"price": 3.99,
"brand": "Tree milk",
},
{
"id": 90,
"title": "Kiwi",
"description": "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
"category": "groceries",
"price": 2.49,
"brand": "Fol",
},
{
"id": 91,
"title": "Cucumber",
"description": "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
"category": "groceries",
"price": 1.49,
"brand": "Mamu",
},
{
"id": 92,
"title": "Dog Food",
"description": "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
"category": "groceries",
"price": 10.99,
"brand": "Dogeshvai",
},
{
"id": 93,
"title": "Eggs",
"description": "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
"category": "groceries",
"price": 2.99,
"brand": "Chicken or Egg",
},
{
"id": 94,
"title": "Fish Steak",
"description": "Quality fish steak, suitable for grilling, baking, or pan-searing.",
"category": "groceries",
"price": 14.99,
"brand": "Fish",
},
{
"id": 95,
"title": "Green Bell Pepper",
"description": "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
"category": "groceries",
"price": 1.29,
"brand": "Kacha Bazzar",
},
{
"id": 96,
"title": "Green Chili Pepper",
"description": "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
"category": "groceries",
"price": 0.99,
"brand": "Kacha Bazaar",
},
{
"id": 97,
"title": "Honey Jar",
"description": "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
"category": "groceries",
"price": 6.99,
"brand": "Machir Juice",
},
{
"id": 98,
"title": "Ice Cream",
"description": "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
"category": "groceries",
"price": 5.49,
"brand": "Cow Ice",
},
{
"id": 99,
"title": "Juice",
"description": "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
"category": "groceries",
"price": 3.99,
"brand": "Tree milk",
},
{
"id": 100,
"title": "Kiwi",
"description": "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
"category": "groceries",
"price": 2.49,
"brand": "Fol",
}
]
export default Product
